services:

  application:
    build:
      context: ../application
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:16-alpine
    ports:
      - "45432:5432"
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env


volumes:
  db_value:
